spring.application.name=gymmanager

spring.datasource.url=jdbc:postgresql://localhost:5432/gymdb
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#dockers
#spring.datasource.url=jdbc:postgresql://localhost:5432/gymdb
#spring.datasource.username=gymuser
#spring.datasource.password=gympass